export const PRODUCTS = [
    {
        "id": 0,
        "name": "Rose and Lavender Spray",
        "description": "This spray is made from rose and lavender water that is made from organic rose and lavender petals. This spray also has glycerine for an extra moisturizing effect.",
        "price": "6.99",
        "options": [],
        "type": "Skincare",
        "catagory": "Featured",
        "image": ".\\assets\\products\\Rose and Lavender Spray1x1.jpg",
        "sold_out": true,
        "sale": true,
        "sale_price": "3.00",
        "disable": false
    },
    {
        "id": 1,
        "name": "Mini Hand Sanitizers",
        "description": "Cucumber Melon scented. Formulated with 91% Rubbing Alcohol, Hydrogen Peroxide, Aloe Vera gel, Glycerine, Lavender and Tea Tree essential oil.",
        "price": "3.50",
        "options": [],
        "type": "Skincare",
        "catagory": "Featured",
        "image": ".\\assets\\products\\MiniHandSanitizers1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 2,
        "name": "Mother’s Day $10 Bundle",
        "description": "Includes choice of Face and Body Scrub or Hair and Body Butter, Rose Lip Oil or Lip Gloss, and Lip Balm or Cuticle Naim Oil Pen. Include your specific choices in the notes or instructions section.",
        "price": "10.00",
        "options": [],
        "type": "Promotional Items",
        "catagory": "Promotion",
        "image": ".\\assets\\products\\MothersDay101x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 3,
        "name": "Mother’s Day $15 Bundle",
        "description": "This Bundle includes a Lip balm and Cuticle Oil Pen as well as a choice of Face and Body Scrub or Hair and Body Butter, and a choice of Lip Gloss or Rose Lip Oil. Gift bag and Confetti Included. Include your specific choices in the notes or instructions section.",
        "price": "15.00",
        "options": [],
        "type": "Promotional Items",
        "catagory": "Promotion",
        "image": ".\\assets\\products\\MothersDay151x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 4,
        "name": "Mother’s Day $25 Bundle",
        "description": "This Bundle includes a Lip balm and Cuticle Oil Pen as well as a choice of Face and Body Scrub or Hair and Body Butter, and a choice of Lip Gloss or Rose Lip Oil. Gift bag and Confetti Included. Include your specific choices in the notes or instructions section.",
        "price": "25.00",
        "options": [],
        "type": "Promotional Items",
        "catagory": "Promotion",
        "image": ".\\assets\\products\\MothersDay251x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 5,
        "name": "Whipped Face & Body Butter",
        "description": "Cucumber Melon Scented",
        "price": "7.99",
        "options": [],
        "type": "Skincare",
        "catagory": "Featured",
        "image": ".\\assets\\products\\WhippedFaceandBodyButter1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 6,
        "name": "Vanilla Rose Face & Body Scrub",
        "description": "",
        "price": "7.99",
        "options": [],
        "type": "Bath & Body",
        "catagory": "",
        "image": ".\\assets\\products\\VanillaRoseFace&BodyScrub1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 7,
        "name": "Strawberry Lip Balm",
        "description": "Moisturizing lip balm formulated with shea butter and a blend of natural oils.",
        "price": "2.99",
        "options": [],
        "type": "Lip Balms",
        "catagory": "",
        "image": ".\\assets\\products\\StrawberryLipBalm1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 8,
        "name": "Rose Nail Oil Twist Pen",
        "description": "",
        "price": "3.50",
        "options": [],
        "type": "Growth Serums",
        "catagory": "",
        "image": ".\\assets\\products\\RoseNailOilTwistPen1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 9,
        "name": "Eyelash & Eyebrow Growth Serum",
        "description": "",
        "price": "6.50",
        "options": [],
        "type": "Growth Serums",
        "catagory": "",
        "image": ".\\assets\\products\\EyelashandEyebrowGrowthSerum1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 10,
        "name": "Rose Petal Lip Oil",
        "description": "",
        "price": "4.99",
        "options": [],
        "type": "Lip Oil",
        "catagory": "",
        "image": ".\\assets\\products\\RosePetalLipOil1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 11,
        "name": "Klarity",
        "description": "",
        "price": "3.99",
        "options": [],
        "type": "Lip Gloss",
        "catagory": "",
        "image": ".\\assets\\products\\Klarity1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 12,
        "name": "Cotton Candy Lip Scrub",
        "description": "",
        "price": "3.99",
        "options": [],
        "type": "Lip Scrubs",
        "catagory": "",
        "image": ".\\assets\\products\\CottonCandyLipScrub1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 13,
        "name": "Juicy",
        "description": "",
        "price": "3.99",
        "options": [],
        "type": "Lip Gloss",
        "catagory": "",
        "image": ".\\assets\\products\\Juicy1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 14,
        "name": "Nude Collection",
        "description": "",
        "price": "3.99",
        "options": ["Dusty Rose","Teddy","Bare","Mahogany"],
        "type": "Lip Gloss",
        "catagory": "",
        "image": ".\\assets\\products\\NudeCollection1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 15,
        "name": "Mango Lip Scrub",
        "description": "",
        "price": "3.99",
        "options": [],
        "type": "Lip Scrubs",
        "catagory": "",
        "image": ".\\assets\\products\\MangoLipScrub1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 16,
        "name": "Princess",
        "description": "",
        "price": "3.99",
        "options": [],
        "type": "Lip Gloss",
        "catagory": "",
        "image": ".\\assets\\products\\Princess1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 17,
        "name": "Melon Lip Scrub",
        "description": "",
        "price": "3.99",
        "options": [],
        "type": "Lip Scrubs",
        "catagory": "",
        "image": ".\\assets\\products\\MelonLipScrub1x1.jpg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    },
    {
        "id": 18,
        "name": "Baby",
        "description": "",
        "price": "3.99",
        "options": [],
        "type": "Lip Gloss",
        "catagory": "",
        "image": ".\\assets\\products\\Baby.jpeg",
        "sold_out": false,
        "sale": false,
        "sale_price": "",
        "disable": false
    }
    
]